services:
  - type: web
    name: smart-face-recognition
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python gradio/app.py
    envVars:
      - key: PORT
        value: 8000
